<?xml version="1.0" encoding="UTF-8" ?>
<Package name="Quiz" format_version="5">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs>
        <Dialog name="quiz_dlg" src="quiz_dlg/quiz_dlg.dlg" />
    </Dialogs>
    <Resources>
        <File name="change_screen" src="html/change_screen.ogg" />
        <File name="quiz-end" src="html/en/quiz-end.html" />
        <File name="quiz-start-en" src="html/en/quiz-start-en.html" />
        <File name="quiz-start-fin" src="html/en/quiz-start-fin.html" />
        <File name="quiz1" src="html/en/quiz1.html" />
        <File name="quiz10" src="html/en/quiz10.html" />
        <File name="quiz10_ans" src="html/en/quiz10_ans.html" />
        <File name="quiz10_info" src="html/en/quiz10_info.html" />
        <File name="quiz11" src="html/en/quiz11.html" />
        <File name="quiz11_ans" src="html/en/quiz11_ans.html" />
        <File name="quiz11_info" src="html/en/quiz11_info.html" />
        <File name="quiz12" src="html/en/quiz12.html" />
        <File name="quiz12_ans" src="html/en/quiz12_ans.html" />
        <File name="quiz12_info" src="html/en/quiz12_info.html" />
        <File name="quiz13" src="html/en/quiz13.html" />
        <File name="quiz13_ans" src="html/en/quiz13_ans.html" />
        <File name="quiz13_info" src="html/en/quiz13_info.html" />
        <File name="quiz14" src="html/en/quiz14.html" />
        <File name="quiz14_ans" src="html/en/quiz14_ans.html" />
        <File name="quiz14_info" src="html/en/quiz14_info.html" />
        <File name="quiz15" src="html/en/quiz15.html" />
        <File name="quiz15_ans" src="html/en/quiz15_ans.html" />
        <File name="quiz15_info" src="html/en/quiz15_info.html" />
        <File name="quiz1_ans" src="html/en/quiz1_ans.html" />
        <File name="quiz1_info" src="html/en/quiz1_info.html" />
        <File name="quiz2" src="html/en/quiz2.html" />
        <File name="quiz2_ans" src="html/en/quiz2_ans.html" />
        <File name="quiz2_info" src="html/en/quiz2_info.html" />
        <File name="quiz3" src="html/en/quiz3.html" />
        <File name="quiz3_ans" src="html/en/quiz3_ans.html" />
        <File name="quiz3_info" src="html/en/quiz3_info.html" />
        <File name="quiz4" src="html/en/quiz4.html" />
        <File name="quiz4_ans" src="html/en/quiz4_ans.html" />
        <File name="quiz4_info" src="html/en/quiz4_info.html" />
        <File name="quiz5" src="html/en/quiz5.html" />
        <File name="quiz5_ans" src="html/en/quiz5_ans.html" />
        <File name="quiz5_info" src="html/en/quiz5_info.html" />
        <File name="quiz6" src="html/en/quiz6.html" />
        <File name="quiz6_ans" src="html/en/quiz6_ans.html" />
        <File name="quiz6_info" src="html/en/quiz6_info.html" />
        <File name="quiz7" src="html/en/quiz7.html" />
        <File name="quiz7_ans" src="html/en/quiz7_ans.html" />
        <File name="quiz7_info" src="html/en/quiz7_info.html" />
        <File name="quiz8" src="html/en/quiz8.html" />
        <File name="quiz8_ans" src="html/en/quiz8_ans.html" />
        <File name="quiz8_info" src="html/en/quiz8_info.html" />
        <File name="quiz9" src="html/en/quiz9.html" />
        <File name="quiz9_ans" src="html/en/quiz9_ans.html" />
        <File name="quiz9_info" src="html/en/quiz9_info.html" />
        <File name="quiz-end" src="html/fin/quiz-end.html" />
        <File name="quiz-start-fin" src="html/fin/quiz-start-fin.html" />
        <File name="quiz1" src="html/fin/quiz1.html" />
        <File name="quiz10" src="html/fin/quiz10.html" />
        <File name="quiz10_ans" src="html/fin/quiz10_ans.html" />
        <File name="quiz10_info" src="html/fin/quiz10_info.html" />
        <File name="quiz11" src="html/fin/quiz11.html" />
        <File name="quiz11_ans" src="html/fin/quiz11_ans.html" />
        <File name="quiz11_info" src="html/fin/quiz11_info.html" />
        <File name="quiz12" src="html/fin/quiz12.html" />
        <File name="quiz12_ans" src="html/fin/quiz12_ans.html" />
        <File name="quiz12_info" src="html/fin/quiz12_info.html" />
        <File name="quiz13" src="html/fin/quiz13.html" />
        <File name="quiz13_ans" src="html/fin/quiz13_ans.html" />
        <File name="quiz13_info" src="html/fin/quiz13_info.html" />
        <File name="quiz14" src="html/fin/quiz14.html" />
        <File name="quiz14_ans" src="html/fin/quiz14_ans.html" />
        <File name="quiz14_info" src="html/fin/quiz14_info.html" />
        <File name="quiz15" src="html/fin/quiz15.html" />
        <File name="quiz15_ans" src="html/fin/quiz15_ans.html" />
        <File name="quiz15_info" src="html/fin/quiz15_info.html" />
        <File name="quiz1_ans" src="html/fin/quiz1_ans.html" />
        <File name="quiz1_info" src="html/fin/quiz1_info.html" />
        <File name="quiz2" src="html/fin/quiz2.html" />
        <File name="quiz2_ans" src="html/fin/quiz2_ans.html" />
        <File name="quiz2_info" src="html/fin/quiz2_info.html" />
        <File name="quiz3" src="html/fin/quiz3.html" />
        <File name="quiz3_ans" src="html/fin/quiz3_ans.html" />
        <File name="quiz3_info" src="html/fin/quiz3_info.html" />
        <File name="quiz4" src="html/fin/quiz4.html" />
        <File name="quiz4_ans" src="html/fin/quiz4_ans.html" />
        <File name="quiz4_info" src="html/fin/quiz4_info.html" />
        <File name="quiz5" src="html/fin/quiz5.html" />
        <File name="quiz5_ans" src="html/fin/quiz5_ans.html" />
        <File name="quiz5_info" src="html/fin/quiz5_info.html" />
        <File name="quiz6" src="html/fin/quiz6.html" />
        <File name="quiz6_ans" src="html/fin/quiz6_ans.html" />
        <File name="quiz6_info" src="html/fin/quiz6_info.html" />
        <File name="quiz7" src="html/fin/quiz7.html" />
        <File name="quiz7_ans" src="html/fin/quiz7_ans.html" />
        <File name="quiz7_info" src="html/fin/quiz7_info.html" />
        <File name="quiz8" src="html/fin/quiz8.html" />
        <File name="quiz8_ans" src="html/fin/quiz8_ans.html" />
        <File name="quiz8_info" src="html/fin/quiz8_info.html" />
        <File name="quiz9" src="html/fin/quiz9.html" />
        <File name="quiz9_ans" src="html/fin/quiz9_ans.html" />
        <File name="quiz9_info" src="html/fin/quiz9_info.html" />
        <File name="gulpfile" src="html/gulpfile.js" />
        <File name="index" src="html/index.html" />
        <File name="package" src="html/package.json" />
        <File name="bootstrap.min" src="html/site/css/bootstrap.min.css" />
        <File name="pali_style" src="html/site/css/pali_style.css" />
        <File name="style" src="html/site/css/style.css" />
        <File name="arrowdown" src="html/site/img/arrowdown.png" />
        <File name="bgimage" src="html/site/img/bgimage.png" />
        <File name="flag-eng" src="html/site/img/flag-eng.png" />
        <File name="flag-eng2" src="html/site/img/flag-eng2.png" />
        <File name="flag-fi" src="html/site/img/flag-fi.png" />
        <File name="flag-fi2" src="html/site/img/flag-fi2.png" />
        <File name="howtopali" src="html/site/img/howtopali.png" />
        <File name="loading" src="html/site/img/loading.gif" />
        <File name="map-joukkoliikenne" src="html/site/img/map-joukkoliikenne.png" />
        <File name="map-kassa" src="html/site/img/map-kassa.png" />
        <File name="map-kasvatus" src="html/site/img/map-kasvatus.png" />
        <File name="map-kaupunkiymparisto" src="html/site/img/map-kaupunkiymparisto.png" />
        <File name="map-kotitori" src="html/site/img/map-kotitori.png" />
        <File name="map-pysakoinninvalvonta" src="html/site/img/map-pysakoinninvalvonta.png" />
        <File name="map-visit" src="html/site/img/map-visit.png" />
        <File name="map" src="html/site/img/map.png" />
        <File name="pic0" src="html/site/img/pic0.png" />
        <File name="pic1" src="html/site/img/pic1.png" />
        <File name="pic2" src="html/site/img/pic2.png" />
        <File name="quiz-bg-1" src="html/site/img/quiz-bg-1.jpg" />
        <File name="quiz-bg-10" src="html/site/img/quiz-bg-10.jpg" />
        <File name="quiz-bg-11" src="html/site/img/quiz-bg-11.jpg" />
        <File name="quiz-bg-12" src="html/site/img/quiz-bg-12.jpg" />
        <File name="quiz-bg-13" src="html/site/img/quiz-bg-13.jpg" />
        <File name="quiz-bg-14" src="html/site/img/quiz-bg-14.jpg" />
        <File name="quiz-bg-15" src="html/site/img/quiz-bg-15.jpg" />
        <File name="quiz-bg-2" src="html/site/img/quiz-bg-2.jpg" />
        <File name="quiz-bg-3" src="html/site/img/quiz-bg-3.jpg" />
        <File name="quiz-bg-4" src="html/site/img/quiz-bg-4.jpg" />
        <File name="quiz-bg-5" src="html/site/img/quiz-bg-5.jpg" />
        <File name="quiz-bg-6" src="html/site/img/quiz-bg-6.jpg" />
        <File name="quiz-bg-7" src="html/site/img/quiz-bg-7.jpg" />
        <File name="quiz-bg-8" src="html/site/img/quiz-bg-8.jpg" />
        <File name="quiz-bg-9" src="html/site/img/quiz-bg-9.jpg" />
        <File name="quiz-stars" src="html/site/img/quiz-stars.png" />
        <File name="reitti1" src="html/site/img/reitti1.png" />
        <File name="reitti10" src="html/site/img/reitti10.png" />
        <File name="reitti11" src="html/site/img/reitti11.png" />
        <File name="reitti12" src="html/site/img/reitti12.png" />
        <File name="reitti13" src="html/site/img/reitti13.png" />
        <File name="reitti14" src="html/site/img/reitti14.png" />
        <File name="reitti15" src="html/site/img/reitti15.png" />
        <File name="reitti16" src="html/site/img/reitti16.png" />
        <File name="reitti17" src="html/site/img/reitti17.png" />
        <File name="reitti18" src="html/site/img/reitti18.png" />
        <File name="reitti19" src="html/site/img/reitti19.png" />
        <File name="reitti2" src="html/site/img/reitti2.png" />
        <File name="reitti3" src="html/site/img/reitti3.png" />
        <File name="reitti4" src="html/site/img/reitti4.png" />
        <File name="reitti5" src="html/site/img/reitti5.png" />
        <File name="reitti6" src="html/site/img/reitti6.png" />
        <File name="reitti7" src="html/site/img/reitti7.png" />
        <File name="reitti8" src="html/site/img/reitti8.png" />
        <File name="reitti9" src="html/site/img/reitti9.png" />
        <File name="reittiKaikki" src="html/site/img/reittiKaikki.png" />
        <File name="reittiTeisko" src="html/site/img/reittiTeisko.png" />
        <File name="scroll_left_icon" src="html/site/img/scroll_left_icon.jpg" />
        <File name="scroll_right_icon" src="html/site/img/scroll_right_icon.jpg" />
        <File name="scroll_right_icon2" src="html/site/img/scroll_right_icon2.jpg" />
        <File name="tampere_map" src="html/site/img/tampere_map.png" />
        <File name="tampere_map1" src="html/site/img/tampere_map1.png" />
        <File name="tampere_map2" src="html/site/img/tampere_map2.png" />
        <File name="tampere_map3" src="html/site/img/tampere_map3.png" />
        <File name="tampereenkaupunki-logo" src="html/site/img/tampereenkaupunki-logo.png" />
        <File name="tampereenteknillinenyliopisto-logo" src="html/site/img/tampereenteknillinenyliopisto-logo.png" />
        <File name="unspecified" src="html/site/img/unspecified.jpg" />
        <File name="bootstrap.min" src="html/site/js/bootstrap.min.js" />
        <File name="_base" src="html/site/scss/_base.scss" />
        <File name="_default" src="html/site/scss/_default.scss" />
        <File name="_typography" src="html/site/scss/_typography.scss" />
        <File name="style" src="html/site/scss/style.scss" />
        <File name="fontawesome-all.min" src="html/site/web-fonts-with-css/css/fontawesome-all.min.css" />
        <File name="fa-brands-400" src="html/site/web-fonts-with-css/webfonts/fa-brands-400.eot" />
        <File name="fa-brands-400" src="html/site/web-fonts-with-css/webfonts/fa-brands-400.svg" />
        <File name="fa-brands-400" src="html/site/web-fonts-with-css/webfonts/fa-brands-400.ttf" />
        <File name="fa-brands-400" src="html/site/web-fonts-with-css/webfonts/fa-brands-400.woff" />
        <File name="fa-brands-400" src="html/site/web-fonts-with-css/webfonts/fa-brands-400.woff2" />
        <File name="fa-regular-400" src="html/site/web-fonts-with-css/webfonts/fa-regular-400.eot" />
        <File name="fa-regular-400" src="html/site/web-fonts-with-css/webfonts/fa-regular-400.svg" />
        <File name="fa-regular-400" src="html/site/web-fonts-with-css/webfonts/fa-regular-400.ttf" />
        <File name="fa-regular-400" src="html/site/web-fonts-with-css/webfonts/fa-regular-400.woff" />
        <File name="fa-regular-400" src="html/site/web-fonts-with-css/webfonts/fa-regular-400.woff2" />
        <File name="fa-solid-900" src="html/site/web-fonts-with-css/webfonts/fa-solid-900.eot" />
        <File name="fa-solid-900" src="html/site/web-fonts-with-css/webfonts/fa-solid-900.svg" />
        <File name="fa-solid-900" src="html/site/web-fonts-with-css/webfonts/fa-solid-900.ttf" />
        <File name="fa-solid-900" src="html/site/web-fonts-with-css/webfonts/fa-solid-900.woff" />
        <File name="fa-solid-900" src="html/site/web-fonts-with-css/webfonts/fa-solid-900.woff2" />
        <File name="whistle" src="html/sounds/whistle.wav" />
        <File name="whistling" src="html/sounds/whistling.wav" />
        <File name="whistling2" src="html/sounds/whistling2.wav" />
        <File name="yawn" src="html/sounds/yawn.wav" />
        <File name="map" src="html/unusable/map.html" />
        <File name="quiz-end-fin" src="html/unusable/quiz-end-fin.html" />
        <File name="quiz-start-fin" src="html/unusable/quiz-start-fin.html" />
        <File name="quiz1" src="html/unusable/quiz1.html" />
        <File name="services-henkilostokassa-info" src="html/unusable/services-henkilostokassa-info.html" />
        <File name="services-henkilostokassa" src="html/unusable/services-henkilostokassa.html" />
        <File name="services-joukkoliikenne-info" src="html/unusable/services-joukkoliikenne-info.html" />
        <File name="services-joukkoliikenne" src="html/unusable/services-joukkoliikenne.html" />
        <File name="services-kassapalvelut-info" src="html/unusable/services-kassapalvelut-info.html" />
        <File name="services-kassapalvelut" src="html/unusable/services-kassapalvelut.html" />
        <File name="services-kaupunkiymparisto-info" src="html/unusable/services-kaupunkiymparisto-info.html" />
        <File name="services-kaupunkiymparisto" src="html/unusable/services-kaupunkiymparisto.html" />
        <File name="services-kotitori-laitetori-info" src="html/unusable/services-kotitori-laitetori-info.html" />
        <File name="services-kotitori-laitetori" src="html/unusable/services-kotitori-laitetori.html" />
        <File name="services-pysakointivalvonta-info" src="html/unusable/services-pysakointivalvonta-info.html" />
        <File name="services-pysakointivalvonta" src="html/unusable/services-pysakointivalvonta.html" />
        <File name="services-varhaiskasvatus-info" src="html/unusable/services-varhaiskasvatus-info.html" />
        <File name="services-varhaiskasvatus" src="html/unusable/services-varhaiskasvatus.html" />
        <File name="services" src="html/unusable/services.html" />
        <File name="start-fin" src="html/unusable/start-fin.html" />
        <File name="icon" src="icon.png" />
    </Resources>
    <Topics>
        <Topic name="quiz_dlg_enu" src="quiz_dlg/quiz_dlg_enu.top" topicName="quiz_dlg" language="en_US" nuance="enu" />
        <Topic name="quiz_dlg_fif" src="quiz_dlg/quiz_dlg_fif.top" topicName="quiz_dlg" language="fi_FI" nuance="fif" />
    </Topics>
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
        <Translation name="translation_fi_FI" src="translations/translation_fi_FI.ts" language="fi_FI" />
    </Translations>
</Package>
